### PR TITLE
Removes mathjax loading from cdn

### PR DESCRIPTION
**Pull request by liaham**
Since drawio version 10.7.4 (03-JUN-2019) mathjax codebase is included in
drawio/src/main/webapp/math directory.

redmine_drawio_mathjax

There is no need to double include mathjax via this plugin anymore. Therefore, I removed the cdn loading making it also more secure due to possible Cross-Site Scripting vulnerabilities in hostet libraries on cdnjs.cloudflare.com.

I would appreciate it if you could merge this patch, assuming there are no objections.

### CODE REVIEW

**Comment by liaham** [comment]
Hi  @mikitex70,

this commit [8c9bc49](https://github.com/mikitex70/redmine_drawio/pull/138/commits/8c9bc49fd6c9f675f9b03ec574ec206af9a5dffa) was not intended to be submitted. Let me know when you won't remove it by your self. I will recreate the PR without it.

Best Regards,
@liaham

**Comment by mikitex70** [comment]
Hi @liaham, thank you for your work.
I will make a new version soon.

**Comment by liaham** [comment]
Great!

I am currently preparing a new feature supporting the various drawio UI (https://www.drawio.com/blog/diagram-editor-theme) as user preference.

Moreover, the plugin is not compatible with Redmine 6. I would fix that too. 

Do you think the drawio UI feature should be released with Redmine 6 compatability or as an extra feature release before?

**Comment by mikitex70** [comment]
It would be better to separate the features, so that we can distinguish what belongs to UI improvement and what belongs to Redmine 6 support (I discovered the new version today).
Thank you for your work, always very neat. I don't have much time to work on this plugin, and moreover my company is thinking of switching from Redmine to Jira, so I feel even less motivated.

**Pull request merged**
